sidebar_title: "Shu Yu Mo's."
sidebar_subtitle: "YTQ 貓貓 數學 程式碼"

truncate_len: 50

rss: atom.xml

favicon: /img/favicon.ico

# Customize the sidebar nav menu
menu:
    Search: /search
    Categories: /categories
    Tags: /tags
    Archive: /archives
    About: /about

cdn:
    # Support public CDN names: cdnjs, loli, baomitu, unpkg, jsdelivr
    libs: cdnjs
    # The base URL of Google Fonts CDN (e.g. "https://fonts.loli.net" "https://fonts.googleapis.com")
    fonts: https://fonts.loli.net

hljsTheme:
    light: atom-one-light
    dark: atom-one-dark

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] for livere.com
disqus: # [short_name] for disqus.com
giscus:
    # Use the official giscus app
    app: https://giscus.app/client.js

    # The options, see "Enable giscus" section in https://giscus.app/
    repo: ShuYuMo2003/ShuYuMo2003.github.io # [ENTER REPO HERE]
    repo-id: MDEwOlJlcG9zaXRvcnkyOTMyMjg2NDc= # [ENTER REPO ID HERE]
    category: General # [ENTER CATEGORY NAME HERE]
    category-id: DIC_kwDOEXpQZ84CdJZB # [ENTER CATEGORY ID HERE]
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 1
    theme: light
    lang: en
