sidebar_title: "ce-amtic's."
sidebar_subtitle: "隻言片語<br>於此匯聚"

truncate_len: 200

rss: atom.xml

favicon: /img/favicon.ico

# Customize the sidebar nav menu
menu:
    Search: /search
    Archive: /archives
    Tags: /tags
    About: /about

cdn:
    # Support public CDN names: cdnjs, loli, baomitu, unpkg, jsdelivr
    libs: jsdelivr
    # The base URL of Google Fonts CDN (e.g. "https://fonts.loli.net")
    fonts: https://fonts.googleapis.com
    # fonts: https://cdn.menci.xyz/fonts

hljsTheme: atom-one-light

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] for livere.com
disqus: cablogs-1 # [short_name] for disqus.com
giscus:
    # Use the official giscus app
    app: https://giscus.app/client.js

    # The options, see "Enable giscus" section in https://giscus.app/
    repo: # [ENTER REPO HERE]
    repo-id: # [ENTER REPO ID HERE]
    category: # [ENTER CATEGORY NAME HERE]
    category-id: # [ENTER CATEGORY ID HERE]
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    theme: light
    lang: en
